## Scalar, Matrix and Vectors
### Scalar

In [8]:
import numpy as np

In [ ]:
s = 5

In [6]:
s

5

### Vector

In [9]:
n = np.array([2,3,5])
n

array([2, 3, 5])

### Matrix

In [11]:
age = np.array([[23,567,8],[12,5,8]])
age

array([[ 23, 567,   8],
       [ 12,   5,   8]])

## Tensorflow
### Creating a Tensor

In [13]:
m1 = np.array([2,3,5])
m1

array([2, 3, 5])

In [14]:
m2 = np.array([4,7,9])

In [15]:
t = np.array([m1,m2])
t

array([[2, 3, 5],
       [4, 7, 9]])

In [16]:
m1 + m2

array([ 6, 10, 14])

### Why is linear Algebra Useful?
- Vectorlizing code
- Image Recognition
- Dimentionality reduction 